// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisionGate.Data;

#nullable disable

namespace VisionGate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619133421_RemoveRedundantFields")]
    partial class RemoveRedundantFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisionGate.Models.CheckInRecord", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInId"));

                    b.Property<string>("CheckInImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FaceConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CheckInId");

                    b.HasIndex("CheckInTime");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EmployeeId", "CheckInTime");

                    b.ToTable("CheckInRecords");
                });

            modelBuilder.Entity("VisionGate.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("VisionGate.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("FaceEmbedding")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FaceImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("ShiftId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("VisionGate.Models.PPEDetection", b =>
                {
                    b.Property<int>("PPEDetectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PPEDetectionId"));

                    b.Property<int?>("CheckInId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetectionData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasGloves")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHelmet")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMask")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSafetyBoots")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSafetyVest")
                        .HasColumnType("bit");

                    b.Property<bool>("OverallCompliance")
                        .HasColumnType("bit");

                    b.HasKey("PPEDetectionId");

                    b.HasIndex("CheckInId")
                        .IsUnique()
                        .HasFilter("[CheckInId] IS NOT NULL");

                    b.ToTable("PPEDetections");
                });

            modelBuilder.Entity("VisionGate.Models.ShiftConfig", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("ShiftConfigs");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            Description = "Ca làm việc mặc định",
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            ShiftName = "Ca Hành Chính",
                            StartTime = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("VisionGate.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VisionGate.Models.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int?>("PPEDetectionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int");

                    b.Property<int>("ViolationType")
                        .HasColumnType("int");

                    b.HasKey("ViolationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsResolved");

                    b.HasIndex("PPEDetectionId");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("VisionGate.Models.CheckInRecord", b =>
                {
                    b.HasOne("VisionGate.Models.Device", "Device")
                        .WithMany("CheckInRecords")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VisionGate.Models.Employee", "Employee")
                        .WithMany("CheckInRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("VisionGate.Models.Employee", b =>
                {
                    b.HasOne("VisionGate.Models.ShiftConfig", "ShiftConfig")
                        .WithMany("Employees")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftConfig");
                });

            modelBuilder.Entity("VisionGate.Models.PPEDetection", b =>
                {
                    b.HasOne("VisionGate.Models.CheckInRecord", "CheckInRecord")
                        .WithOne("PPEDetection")
                        .HasForeignKey("VisionGate.Models.PPEDetection", "CheckInId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CheckInRecord");
                });

            modelBuilder.Entity("VisionGate.Models.Violation", b =>
                {
                    b.HasOne("VisionGate.Models.PPEDetection", "PPEDetection")
                        .WithMany("Violations")
                        .HasForeignKey("PPEDetectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VisionGate.Models.User", "ResolvedByUser")
                        .WithMany("ResolvedViolations")
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PPEDetection");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("VisionGate.Models.CheckInRecord", b =>
                {
                    b.Navigation("PPEDetection");
                });

            modelBuilder.Entity("VisionGate.Models.Device", b =>
                {
                    b.Navigation("CheckInRecords");
                });

            modelBuilder.Entity("VisionGate.Models.Employee", b =>
                {
                    b.Navigation("CheckInRecords");
                });

            modelBuilder.Entity("VisionGate.Models.PPEDetection", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("VisionGate.Models.ShiftConfig", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("VisionGate.Models.User", b =>
                {
                    b.Navigation("ResolvedViolations");
                });
#pragma warning restore 612, 618
        }
    }
}
